vim.keymap.set("n", "<leader>s", "<Cmd>nohlsearch<CR>")
vim.keymap.set("n", "<Tab>q", "<Cmd>bdelete<CR>")
vim.keymap.set("n", "<Tab>Q", "<Cmd>bdelete!<CR>")
vim.keymap.set("n", "<F12>p", "<Cmd>Lazy<CR>")
vim.keymap.set("i", "jk", "<Esc>")
